config/routes.rb
Rails.application.routes.draw do

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :occurs_at, :location, presence: true
  validates :location, length: { minimum: 5 }

  validates :location, uniqueness: { scope: :occurs_at,
                                     message: 'An event has already been scheduled at that time',
                                     case_sensitive: false }

  has_many :movies
  has_many :votes
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, :url, presence: true

  has_many :votes
  belongs_to :event
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :person, presence: true

  belongs_to :event
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event created successfully'
    else
      render :new, notice: @event.errors
    end
end

  def update
  end

  def destroy
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:location, :occurs_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to "Create Event", new_event_path %>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Date/Time</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.location %></td>
        <td><%= event.occurs_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New Events</h1>

<%= form_for(@event) do |f| %>
  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :occurs_at, 'Date/Time' %>
  <%= f.text_field :occurs_at %>

  <%= f.submit %>

<% end %>

app/views/events/show.html.erb
<%= @event.location %>
<%= @event.occurs_at %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieNight</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>